" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color2 = '#EFB080'
let s:Color12 = '#505050'
let s:Color7 = '#747474'
let s:Color6 = '#141414'
let s:Color8 = '#1a1a1a'
let s:Color1 = '#83D6C5'
let s:Color11 = '#303030'
let s:Color13 = '#ffffff'
let s:Color4 = '#E394DC'
let s:Color3 = '#82D2CE'
let s:Color9 = '#d8dee9'
let s:Color0 = '#D6D6DD'
let s:Color5 = '#EBC88D'
let s:Color10 = '#383838'

call s:highlight('Operator', '', s:Color0, '')
call s:highlight('Keyword', '', s:Color1, '')
call s:highlight('Identifier', '', s:Color0, '')
call s:highlight('Function', '', s:Color2, '')
call s:highlight('Type', '', s:Color2, '')
call s:highlight('Type', '', s:Color3, '')
call s:highlight('String', '', s:Color4, '')
call s:highlight('Number', '', s:Color5, '')
call s:highlight('StatusLine', s:Color7, s:Color6, '')
call s:highlight('WildMenu', s:Color8, s:Color9, '')
call s:highlight('Pmenu', s:Color8, s:Color9, '')
call s:highlight('PmenuSel', s:Color9, s:Color8, '')
call s:highlight('PmenuThumb', s:Color8, s:Color9, '')
call s:highlight('DiffAdd', s:Color10, '', '')
call s:highlight('DiffDelete', s:Color10, '', '')
call s:highlight('Normal', s:Color8, s:Color9, '')
call s:highlight('Visual', s:Color11, '', '')
call s:highlight('CursorLine', s:Color11, '', '')
call s:highlight('ColorColumn', s:Color11, '', '')
call s:highlight('SignColumn', s:Color8, '', '')
call s:highlight('LineNr', '', s:Color12, '')
call s:highlight('TabLine', s:Color6, s:Color12, '')
call s:highlight('TabLineSel', s:Color13, s:Color8, '')
call s:highlight('TabLineFill', s:Color6, s:Color12, '')
call s:highlight('TSPunctDelimiter', '', s:Color9, '')

highlight! link TSNumber Number
highlight! link NonText Comment
highlight! link TSType Type
highlight! link TSPunctBracket MyTag
highlight! link CursorLineNr Identifier
highlight! link Whitespace Comment
highlight! link TSNamespace TSType
highlight! link TSFunction Function
highlight! link Conditional Operator
highlight! link TSField Constant
highlight! link TelescopeNormal Normal
highlight! link Macro Function
highlight! link TSParameterReference TSParameter
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TSFloat Number
highlight! link TSOperator Operator
highlight! link TSRepeat Repeat
highlight! link TSTag MyTag
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSParameter Constant
highlight! link TSLabel Type
highlight! link TSConstant Constant
highlight! link TSKeyword Keyword
highlight! link Folded Comment
highlight! link TSComment Comment
highlight! link TSString String
highlight! link Operator Keyword
highlight! link TSConditional Conditional
highlight! link TSTagDelimiter Type
highlight! link TSFuncMacro Macro
highlight! link TSProperty TSField
highlight! link Repeat Conditional
